Disable S390X
```
$ yum -y install glibc-static openssl-devel tar
Error:  Multilib version problems found. This often means that the root
  cause is something else and multilib version checking is just
  pointing out that there is a problem.
Protected multilib versions: zlib-1.2.7-19.el7_9.s390 != zlib-1.2.11-21.el7.s390x
```